export const POKEMON_SYNC_START_DATE = '2024-01-01'
export const SYNCED_BOOSTER_LIMIT = 24
export const PACK_OPEN_COOLDOWN_SECONDS = 2 * 60 * 60
export const SANDBOX_PACK_OPEN_MIN_YEAR = 2003
export const SANDBOX_PACK_OPEN_MAX_YEAR = 2022
export const SANDBOX_PACK_OPEN_COOLDOWN_SECONDS = 5
