export const TRADE_AUCTION_DURATION_MS = 7 * 24 * 60 * 60 * 1000
export const MAX_ACTIVE_AUCTIONS_PER_USER = 3
export const MAX_PENDING_OFFERS_PER_AUCTION_BY_USER = 5
export const MAX_FILTER_LIST_LENGTH = 100
export const MAX_REQUIREMENT_LIST_LENGTH = 100
export const MAX_OFFER_CARDS_PER_REQUEST = 100
export const MAX_OFFER_CARD_QUANTITY = 10_000
export const TRADE_LIST_LIMIT = 100
